---
config:
  Ptx: 16 # en dBm
  frecuencia: 1000 # en MHz
  distancia: 10 # en Km
  perdida_conector: 0.25
  perdida_cable: 0.1
  ht: 50
  hr: 50
  Gtx: 27
  Grx: 27
  FM:
    R: 0.99999
    A: 1
    B: 1